// Here define all the action types

export const actionTypes = {
  FETCH_ALL_FILTERS: "FETCH_ALL_FILTERS",
  TOGGLE_FILTER: "TOGGLE_FILTER",
  SET_PRODUCTS: "SET_PRODUCTS",
  FILTER_EXPAND: "FILTER_EXPAND",
  FILTER_VIEW_MORE: "FILTER_VIEW_MORE",
  REMOVE_FILTERS: "REMOVE_FILTERS",
  SELECT_TAB: "SELECT_TAB",
  FETCH_FILTERED_PRODUCTS: "FETCH_FILTERED_PRODUCTS",
  UPDATE_SORTING: "UPDATE_SORTING",
  ADD_MORE_PRODUCTS: "ADD_MORE_PRODUCTS",
  CHANGE_QUANTITY: "CHANGE_QUANTITY",
  REMOVE_PRODUCTS: "REMOVE_PRODUCTS",
  ADD_ITEMS: "ADD_ITEMS",
  EDIT_CART: "EDIT_CART",
  MERGE_CART_ITEMS: "MERGE_CART_ITEMS",
  FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
  FETCH_CART_ERROR: "FETCH_CART_ERROR",
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",

  SET_INVENTORY: "SET_INVENTORY",
  SET_CARTID: "SET_CARTID",
  SET_USERID: "SET_USERID",
  SAVE_FOR_LATER: "SAVE_FOR_LATER",
  ADD_BACK_TO_CART: "ADD_BACK_TO_CART",
  FETCH_SAVED_ITEMS_FROM_SERVER: "FETCH_SAVED_ITEMS_FROM_SERVER",

  // shipping address related
  GET_SHIPPING_ADDRESS: "GET_SHIPPING_ADDRESS",
  SELECT_ADDRESS: "SELECT_ADDRESS",

  // shopping cart actions - tax and costs related
  SET_SHIPPING_COST: "SET_SHIPPING_COST",
  SET_TAX_RATE: "SET_TAX_RATE",
  SET_TAX_AMOUNT: "SET_TAX_AMOUNT",
  SET_TOTAL_BEFORE_TAX: "SET_TOTAL_BEFORE_TAX",

  // order related
  SET_ORDER_ID: "SET_ORDER_ID",
  SET_ORDER_ITEMS: "SET_ORDER_ITEMS",
  SET_ORDER_ADDRESS: "SET_ORDER_ADDRESS",
};
